server:
  port: 8080

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:15432/postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: 'false'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'false'

