package com.getdata.dataprovider.entity;

public enum TypeFinancings {

    FINANCIAMENTO_AQUISICAO_BENS_VEICULOS_AUTOMOTORES,
    FINANCIAMENTO_AQUISICAO_BENS_OUTROS_BENS,
    FINANCIAMENTO_MICROCREDITO,
    FINANCIAMENTO_RURAL_CUSTEIO,
    FINANCIAMENTO_RURAL_INVESTIMENTO,
    FINANCIAMENTO_RURAL_COMERCIALIZACAO,
    FINANCIAMENTO_RURAL_INDUSTRIALIZACAO,
    FINANCIAMENTO_IMOBILIARIO_SISTEMA_FINANCEIRO_HABITACAO_SFH,
    FINANCIAMENTO_IMOBILIARIO_SISTEMA_FINANCEIRO_HABITACAO_SFI,
    NAO_IDENTIFICADO
}
